// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bangazon.Migrations
{
    [DbContext(typeof(BangazonDbContext))]
    partial class BangazonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bangazon.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Games"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home"
                        });
                });

            modelBuilder.Entity("Bangazon.Models.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DateCreated = new DateTime(2024, 2, 21, 18, 24, 8, 654, DateTimeKind.Local).AddTicks(9783),
                            IsOpen = true,
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            DateCreated = new DateTime(2024, 2, 21, 18, 24, 8, 654, DateTimeKind.Local).AddTicks(9838),
                            IsOpen = true,
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            DateCreated = new DateTime(2024, 2, 21, 18, 24, 8, 654, DateTimeKind.Local).AddTicks(9840),
                            IsOpen = false,
                            PaymentTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            DateCreated = new DateTime(2024, 2, 21, 18, 24, 8, 654, DateTimeKind.Local).AddTicks(9841),
                            IsOpen = true,
                            PaymentTypeId = 4
                        });
                });

            modelBuilder.Entity("Bangazon.Models.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Credit Card"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Debit Card"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Apple Pay"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Paypal"
                        });
                });

            modelBuilder.Entity("Bangazon.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Personal essays",
                            ImageURL = "https://m.media-amazon.com/images/I/41fm2uwWJUL._SY445_SX342_.jpg",
                            Name = "The White Album by Joan Didion",
                            Price = 13m,
                            SellerId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Audio CD",
                            ImageURL = "https://m.media-amazon.com/images/I/71rRNAnVW6L._SL1400_.jpg",
                            Name = "Badmotorfinger by Soundgarden",
                            Price = 10m,
                            SellerId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Description = "Guessing Game",
                            ImageURL = "https://m.media-amazon.com/images/I/81MBgtB-Y8L._AC_SL1500_.jpg",
                            Name = "Taboo",
                            Price = 14m,
                            SellerId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Multi-colored cutting board",
                            ImageURL = "https://fredericksandmae.com/cdn/shop/products/0511_1296x.jpg?v=1631229005",
                            Name = "Confetti Cutting Board",
                            Price = 70m,
                            SellerId = 4
                        });
                });

            modelBuilder.Entity("Bangazon.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirebaseKey")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSeller")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1675 E Altadena Dr, Altadena, CA",
                            Email = "brandonwalsh74@gmail.com",
                            FirebaseKey = "npAVsfejgPZyg1q0OEKHq6l9zur2",
                            FirstName = "Brandon",
                            IsSeller = false,
                            LastName = "Walsh",
                            UserName = "branman"
                        },
                        new
                        {
                            Id = 2,
                            Address = "3959 Longridge Ave Sherman Oaks, CA",
                            Email = "kelltaylor@hotmail.com",
                            FirebaseKey = "key2",
                            FirstName = "Kelly",
                            IsSeller = true,
                            LastName = "Taylor",
                            UserName = "kells90210"
                        },
                        new
                        {
                            Id = 3,
                            Address = "1605 E. Altadena Dr, Altadena, CA",
                            Email = "dmckay74@aol.com",
                            FirebaseKey = "key3",
                            FirstName = "Dylan",
                            IsSeller = false,
                            LastName = "McKay",
                            UserName = "dmckay"
                        },
                        new
                        {
                            Id = 4,
                            Address = "1060 Brooklawn Dr., Bel Air CA",
                            Email = "dmartin@gmail.com",
                            FirebaseKey = "key4",
                            FirstName = "Donna",
                            IsSeller = false,
                            LastName = "Martin",
                            UserName = "donnaloves2shop"
                        });
                });

            modelBuilder.Entity("OrdersProducts", b =>
                {
                    b.Property<int>("OrdersId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductsId")
                        .HasColumnType("integer");

                    b.HasKey("OrdersId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OrdersProducts");
                });

            modelBuilder.Entity("OrdersProducts", b =>
                {
                    b.HasOne("Bangazon.Models.Orders", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangazon.Models.Products", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
